In [1]:
from skimage import io
import numpy as np
import os
import pandas as pd
import seaborn as sns

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
folder = '../class_data/Apple-20220324T003432Z-001'
images = [os.path.join(root, filename)
          for root, dirs, files in os.walk(folder)
          for filename in files
          if filename.lower().endswith('.jpg')]

ic = []
for img in images:
    ic.append(io.imread(img))

In [4]:
a1 = []
for i in range(len(ic)):
    a1.append(ic[i][:,:,0].flatten())

b1 = np.array([0]*650 + [1] * 650 + [2]*650)

In [5]:
a1 = np.array(a1)
a1.shape

(1950, 76800)

In [6]:
b1

array([0, 0, 0, ..., 2, 2, 2])

In [7]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import RandomForestClassifier
import seaborn as sns
import matplotlib.pyplot as plt

import sys,os
import pandas as pd
import numpy as np

In [8]:
a_train, a_test, b_train, b_test = train_test_split(a1,b1,train_size=0.8)
print(a_train.shape)
print(a_test.shape)
print(b_train.shape)
print(b_test.shape)

(1560, 76800)
(390, 76800)
(1560,)
(390,)



## Logistic Regression


In [13]:
import warnings
warnings.filterwarnings("ignore")
g = LogisticRegression(C=2,random_state=0).fit(a1, b1)
g

LogisticRegression(C=2, random_state=0)

In [18]:
b1_lr_train = g.predict(a_train)

b1_lr_train

print(b1_lr_train.shape)

(1560,)


In [19]:
b1_lr_test = g.predict(a_test)
b1_lr_test
print(b1_lr_test.shape)

(390,)


In [20]:
target_names = ['1', '2','3']

print(classification_report(b_train,b1_lr_train,target_names=target_names))


              precision    recall  f1-score   support

           1       0.82      0.80      0.81       498
           2       0.85      0.84      0.84       542
           3       0.80      0.83      0.81       520

    accuracy                           0.82      1560
   macro avg       0.82      0.82      0.82      1560
weighted avg       0.82      0.82      0.82      1560



In [21]:
target_names = ['1', '2','3']

print(classification_report(b_test,b1_lr_test,target_names=target_names))

              precision    recall  f1-score   support

           1       0.86      0.79      0.82       152
           2       0.76      0.83      0.79       108
           3       0.79      0.80      0.80       130

    accuracy                           0.81       390
   macro avg       0.80      0.81      0.80       390
weighted avg       0.81      0.81      0.81       390



## Confusion Matrix

In [23]:
conf_mat = confusion_matrix(b_train,b1_lr_train)
conf_mat

array([[399,  34,  65],
       [ 43, 453,  46],
       [ 43,  46, 431]], dtype=int64)

In [24]:
conf_mat = confusion_matrix(b_test,b1_lr_test)
conf_mat

array([[120,  16,  16],
       [  7,  90,  11],
       [ 13,  13, 104]], dtype=int64)

## Bias variance

**the values are almost near less bias less variance or we could say the model is not accurate**

